version: '3.3'

services:
  cloud_gateway_service:
    image: abuyusuf/cloud_gateway_service:v3.0
    container_name: cloud_gateway_service
    depends_on:
      - firstms
      - secondms
    ports:
      - 8081:8081
  

  firstms:
    image: abuyusuf/display_service_one:v1.0
    container_name: display_service_one
    expose:
      - 8082
  
  secondms:
    image: abuyusuf/display_service_two:v1.0
    container_name:  display_service_two
    expose:
      - 8083


