version: '3.8'

services:
  cloud_gateway_service:
    image: abuyusuf/abuyusuf/cloud_gateway_service:v1.0
    container_name: cloud_gateway_service
    depends_on:
      - first_ms
      - second_ms
    ports:
      - 8081:8081
  

  first_ms:
    image: abuyusuf/display_service_one:v1.0
    container_name: display_service_one
    expose:
      - 8082
  
  second_ms:
    image: abuyusuf/display_service_two:v1.0
    container_name:  display_service_two
    expose:
      - 8083


